### PR TITLE
fix: expand tsconfig.json include lists, and allow defaulting to it

### LINKED ISSUE #1049: Bug: Can't default includes to tsconfig.json globs
### 🐛 Bug Report

-   TypeStat version: 0.6.0
-   TypeScript version: N/A
-   Node version: N/A

#### Actual Behavior

`typestat.json` config objects that don't have an `include` right now default to the `tsconfig.json` `include` property. But, it isn't expanded like globs: just treated as a hard file list.

#### Expected Behavior

The tsconfig expansions should go through the TypeScript API for expanding TSConfig includes. For example, `"include": ["src"]` should be expanded to the contents of the `src/` directory.

#### Reproduction

```jsonc
// typestat.json
{
    "fixes": {
        "incompleteTypes": true
    }
}
```

```jsonc
// tsconfig.json
{
    "include": ["src"]
}
```

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

-   [x] Addresses an existing issue: fixes #1049
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/TypeStat/labels/status%3A%20accepting%20prs)

## Overview

Uses `ts.parseJsonConfigFileContent` to expand include lists. Unlike the previous `ts.parseJsonConfigFileContent` in the codebase, this one is given a host with methods that actually work in nested directories.

Also defaults `fileNames` to `compilerOptions.include` when not provided.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -70,7 +70,7 @@ export const typeStat = async (argv: TypeStatArgv, output: ProcessOutput): Promi
         if (typeof fileNames !== "object") {
             return {
                 error: new Error(
-                    `Could not run options at index ${i + 1}: ${fileNames ?? `No files included by the 'include' setting were found.`}`,
+                    `Could not run options object ${i + 1}: ${fileNames ?? `No files included by the 'include' setting were found.`}`,
```
Comment (JoshuaKGoldberg) [inline src/index.ts:73]: Slight improvement in the logging: it's the verbal number, not array index...
