### PR TITLE
fix: writing TypeScript config file

### LINKED ISSUE #2113: 🐛 Bug: Writing Multi stage config results having `null` in include files array
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Include array should not contain `null` value

```json
 "include": [
            "test/**/*.{ts,tsx}"
        ]
```

### Actual

```json
 "include": [
            "test/**/*.{ts,tsx}",
            null
        ]
```

### Additional Info

I generated `typestat.json` for this repo by selecting all possible options in improvements section: `Which improvements would you like to make?`

The bug is in `writeSingleTypeScriptConfig` function where `sourceFiles` is not being checked for being present before adding it to array.

It would help to catch bugs if those configs would be type checked. By trying to type check them, I found another possible bug: `printImprovements` adds `inferableTypes: true,` when it should probably be `noInferableTypes`.

My answers

```
✔ What are you trying to accomplish? · Improve typings in my TypeScript files
✔ Where is your tsconfig.json? · ./tsconfig.json
✔ Which improvements would you like to make? · Add missing property declarations to classes, Enable the --noImplicitAny compiler flag, Enable the --noImplicitThis compiler flag, Remove type annotations that don't change the meaning of code, Enable the --strictNullChecks compiler flag

✔ Which glob matches files you'd like to convert? · everything
✔ Which glob matches your test files? · test/**/*.{ts,tsx}
```

Full typestat.json

```json
[
    {
        "fixes": {
            "incompleteTypes": true,
            "noImplicitAny": true,
            "noInferableTypes": true,
            "noImplicitThis": true,
            "strictNonNullAssertions": true
        },
        "projectPath": "./tsconfig.json",
        "types": {
            "strictNullChecks": true
        },
        "include": [
            "test/**/*.{ts,tsx}"
        ]
    },
    {
        "fixes": {
            "incompleteTypes": true,
            "noImplicitAny": true,
            "noInferableTypes": true,
            "noImplicitThis": true
        },
        "projectPath": "./tsconfig.json",
        "exclude": [
            "test/**/*.{ts,tsx}"
        ]
    },
    {
        "fixes": {
            "incompleteTypes": true,
            "noImplicitAny": true,
            "noInferableTypes": true,
            "noImplicitThis": true
        },
        "projectPath": "./tsconfig.json",
        "include": [
            "test/**/*.{ts,tsx}",
            null
        ]
    }
]
```

### PR DESCRIPTION
**Pull request by rubiesonthesky**
## PR Checklist

- [x] Addresses an existing open issue: fixes #2113
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/TypeStat/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

- Fixes issue where `null` was inserted to typestat.json `includes` list
- Fixes issue where option was `inferableTypes` when it should be `noInferableTypes`
- Added basic testing for config generation

For future:
- Config generation is still little bit broken. If I want to select just "Remove type annotations that don't change the meaning of code" option, the generated config file does not have it but instead has just `"incompleteTypes": true`.  -> Needs new issue created. 

🐙

### CODE REVIEW

File: src/initialization/initializeTypeScript/writeMultiTypeScriptConfig.ts [hunk 1]
```diff
@@ -11,61 +12,74 @@ export interface MultiTypeScriptConfigSettings {
...
+		projectPath: project.filePath,
+	};
+
+	const stage3: Partial<RawTypeStatOptions> = {
+		fixes,
+		projectPath: project.filePath,
+	};
+
+	if (testFiles) {
+		// @ts-expect-error Cannot assign to 'include' because it is a read-only property.
```
Comment (JoshuaKGoldberg) [inline src/initialization/initializeTypeScript/writeMultiTypeScriptConfig.ts:52]: [Refactor] For a project that's supposed to migrate over to best TypeScript practices, having a bunch of `// @ts-expect-error`s in source code is probably not the best look 😅. A couple of options here:

* Using a type like [`Writable`](https://github.com/sindresorhus/type-fest/blob/cfb594777f5ede903c151a45c2db250b057902d7/source/writable.d.ts) for the three variables
* Having the variables declare the conditional properties: e.g. in `stage1`, add `include: testFiles ? [testFiles] : undefined`

I personally would go for the latter.

File: src/initialization/initializeTypeScript/writeMultiTypeScriptConfig.ts [hunk 2]
```diff
@@ -11,61 +12,74 @@ export interface MultiTypeScriptConfigSettings {
...
+		stage1.include = [testFiles];
+		// @ts-expect-error Property 'exclude' does not exist on type 'Partial<PendingTypeStatOptions>'.
```
Comment (JoshuaKGoldberg) [inline src/initialization/initializeTypeScript/writeMultiTypeScriptConfig.ts:54]: [Bug] Err, what's going on with `exclude`? It's not used elsewhere - so I think it's another existing bug, right?

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
I appreciate all the added test coverage, this is great!

Requesting changes on some `// @ts-expect-error` removals and a bit of discussion on what might be even more existing issues with the code? (🙃)

**Review by JoshuaKGoldberg — APPROVED** [review]
🔥 This is looking great, thanks a million as usual @rubiesonthesky!
