### PR TITLE
fix: No more adding infinite boolean for function returning promise

### LINKED ISSUE #1284: Bug: Infinite loop adding | boolean to a union typed parameter
### 🐛 Bug Report

-   TypeStat version: current
-   TypeScript version: N/A
-   Node version: v20.3.1

#### Actual Behavior

It looks like TypeStat has ended up in an infinite loop.

#### Expected Behavior

File processed

#### Reproduction

Source javascript file is at https://github.com/micrology/prsm/blob/master/js/prsm.js

typestat.json:
```
cat typestat.json
[
    {
        "files": {
            "renameExtensions": true
        },
        "fixes": {
            "importExtensions": true
        },
        "include": [
            "src/**/*.{js,jsx}"
        ],
        "project": "./tsconfig.json"
    },
    {
        "fixes": {
            "incompleteTypes": true,
            "missingProperties": true,
            "noImplicitAny": true
        },
        "cleanups": {
            "suppressTypeErrors": true
        },
        "include": [
            "src/**/*.{ts,tsx}"
        ],
        "project": "./tsconfig.json"
    }
]%                        
```

Console log:
```
npx typestat --config typestat.json
🚀 Welcome to TypeStat!
⚠️ TypeStat is still very early stage and experimental. ⚠️
While it will improve your code, it will likely add syntax and type errors.
Use TypeStat as a starting point before you manually fix and verify any changes.
TypeStat will run through the 2 options objects specified in typestat.json to modify your source code.
This may take a while...


Starting options object 1 of 2.

Renaming files from JavaScript to TypeScript...
Renamed 1 file from JavaScript to TypeScript.
Done.

Finished options object 1 of 2.


Starting options object 2 of 2.

Starting the core mutation engine. This terminal will log whenever a "wave" of mutations are written to files.
Core mutations will complete when two waves pass with no mutations.
The following fixes will be applied:
	* incompleteTypes
	* missingProperties
	* noImplicitAny

Starting wave 1...
Completed wave 1. Wrote mutations to 1 file.
Starting wave 2...
Completed wave 2. Wrote mutations to 1 file.
Starting wave 3...
Completed wave 3. Wrote mutations to 1 file.
Starting wave 4...
Completed wave 4. Wrote mutations to 1 file.
Starting wave 5...
Completed wave 5. Wrote mutations to 1 file.
Starting wave 6...
Completed wave 6. Wrote mutations to 1 file.
Starting wave 7...
Completed wave 7. Wrote mutations to 1 file.
Starting wave 8...
Completed wave 8. Wrote mutations to 1 file.
Starting wave 9...
Completed wave 9. Wrote mutations to 1 file.
Starting wave 10...
Completed wave 10. Wrote mutations to 1 file.
Starting wave 11...
Completed wave 11. Wrote mutations to 1 file.
Starting wave 12...
Completed wave 12. Wrote mutations to 1 file.
Starting wave 13...
Completed wave 13. Wrote mutations to 1 file.
Starting wave 14...
Completed wave 14. Wrote mutations to 1 file.
Starting wave 15...
Completed wave 15. Wrote mutations to 1 file.
Starting wave 16...
Completed wave 16. Wrote mutations to 1 file.
Starting wave 17...
Completed wave 17. Wrote mutations to 1 file.
Starting wave 18...
Completed wave 18. Wrote mutations to 1 file.
Starting wave 19...
Completed wave 19. Wrote mutations to 1 file.
Starting wave 20...
Completed wave 20. Wrote mutations to 1 file.
Starting wave 21...
Completed wave 21. Wrote mutations to 1 file.
It looks like TypeStat has ended up in an infinite loop.

Bailing out of applying more mutations.

Please file an issue to help us fix the bug for you:

https://github.com/JoshuaKGoldberg/TypeStat

Applying post-fix cleanups...
Done.

Finished options object 2 of 2.


All done! ✨
```

### LINKED ISSUE #1447: Return type duplicate infinite amount: | boolean
### 🐛 Bug Report

-   TypeStat version: 0.7.3
-   TypeScript version: 4.9.5
-   Node version: 20.11

#### Actual Behavior

```ts
declare function navigateByUrl(url: string): Promise<boolean>;

export class exampleDirective {
  async navigateTo(id: number): Promise<boolean> | boolean | boolean | boolean | boolean | boolean {
    return await navigateByUrl(`/page/${id}`);
  }
}
```

#### Expected Behavior

There is no need to change this the return type. This is async function and `Promise<boolean>` should cover that. But also, it should not add `boolean` infinite amount to return types union.

```ts
declare function navigateByUrl(url: string): Promise<boolean>;

export class exampleDirective {
  async navigateTo(id: number): Promise<boolean> {
    return await navigateByUrl(`/page/${id}`);
  }
}
```

#### Reproduction

Original code

```ts
declare function navigateByUrl(url: string): Promise<boolean>;

export class exampleDirective {
  async navigateTo(id: number): Promise<boolean> {
    return await navigateByUrl(`/page/${id}`);
  }
}
```

---

I cloned this repo and added this test case to `test/cases/fixes/incompleteTypes/returnTypes/original.ts` file, and I can see same behavior there.

```ts
    function navigateByUrl(url: string): Promise<boolean>;

    async function navigateTo(id: number): Promise<boolean> {
        return await navigateByUrl(`/page/${id}`);
    }
 ```

After using command `yarn run test:mutation --accept`, I see this in `excepted.ts` and `actual.ts`:

```ts
    function navigateByUrl(url: string): Promise<boolean>;

    async function navigateTo(id: number): Promise<boolean> | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean | boolean {
        return await navigateByUrl(`/page/${id}`);
    }
```

### PR DESCRIPTION
**Pull request by rubiesonthesky**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1447 - I think it also fixes #1284
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/TypeStat/blob/main/.github/CONTRIBUTING.md) were taken 😹 

## Overview

It was this small change in the end??

Note, `async function navigateTo(): Promise<boolean> | boolean {` and `async function navigateTo2(): Promise<boolean> | boolean {` are wrong. Both should return only `Promise<boolean>`. I can remove those from the test but I wanted to keep them to see, the difference.

### CODE REVIEW

File: test/cases/fixes/incompleteTypes/returnTypes/expected.ts [hunk 1]
```diff
@@ -84,4 +84,27 @@
...
+		return await new Promise(() => "");
+	}
+
+	function navigateByUrl(url: string): Promise<boolean>;
+
+	async function navigateTo(): Promise<boolean> | boolean {
+		return await navigateByUrl("");
+	}
+
+	async function navigateTo2(): Promise<boolean> | boolean {
```
Comment (JoshuaKGoldberg) [inline test/cases/fixes/incompleteTypes/returnTypes/expected.ts:98]: > Note, `async function navigateTo(): Promise<boolean> | boolean {` and `async function navigateTo2(): Promise<boolean> | boolean {` are wrong. Both should return only `Promise<boolean>`. I can remove those from the test but I wanted to keep them to see, the difference.

Yeah that looks like an existing unrelated issue. Up for a followup? 😄

File: src/mutations/collecting/flags.ts [hunk 2]
```diff
@@ -6,6 +6,8 @@ import { setSubtract } from "../../shared/sets.js";
 const knownTypeFlagEquivalents = new Map([
 	[ts.TypeFlags.BigInt, ts.TypeFlags.BigIntLiteral],
 	[ts.TypeFlags.BigIntLiteral, ts.TypeFlags.BigInt],
+	[ts.TypeFlags.Boolean, ts.TypeFlags.BooleanLiteral],
+	[ts.TypeFlags.BooleanLiteral, ts.TypeFlags.Boolean],
```
Comment (JoshuaKGoldberg) [inline src/mutations/collecting/flags.ts:10]: > It was this small change in the end??

😄 a lot of these little bugs are! Nice find though, this is a really good fix.

**Review by JoshuaKGoldberg — APPROVED** [review]
Bill and Ted going "EXCELLENT!" and air guitaring at each other

**Comment by JoshuaKGoldberg** [comment]
@all-contributors please add @rubiesonthesky for code.

> 🤖 Beep boop! This comment was added automatically by [all-contributors-auto-action](https://github.com/marketplace/actions/all-contributors-auto-action).
> Not all contributions can be detected from Git & GitHub alone. Please comment any missing contribution types this bot missed.
> ...and of course, thank you for contributing! 💙
