### PR TITLE
feat: add post-fix cleanups

### LINKED ISSUE #1224: 🚀 Feature: Add a "cleanup" fixer, to be used after other fixers
## Overview

Generally speaking, no library will ever be able to completely convert an existing nontrivial JavaScript repository to fully type safe TypeScript on its own. There will always be oddities left over that humans will need to touch up. Bugs, things that are difficult to type out, just plain weird things that rely on odd assumptions out of code - in practice they always exist.

Tools like https://github.com/airbnb/ts-migrate generally work by adding `any`s and/or `// @ts-expect-error`s with big `TODO`-style comments to cover up places that fail type checking. That makes sense as a strategy! People want to finish the initial conversion with a codebase that can `tsc` without error. And they want clear TODOs for necessary cleanups.

Let's add in a new fixer that can add in those `any`s and/or `// @ts-expect-error`s as necessary. It should be able to be run after the existing fixers do their best to fix up types.

### Additional Information

This is likely to be a nontrivial task. I would not recommend it as a `good first issue`, or even a second or third. Implementing this feature will involve a good amount of design work

Thanks @tannerlinsley for prompting me to file this! It'd been back-of-mind for a while, but I'd never gotten around to filing it actionably.

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

-   [x] Addresses an existing issue: fixes #1224
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/TypeStat/labels/status%3A%20accepting%20prs)

## Overview

Adds a _"cleanups"_ section for explicitly running _after_ fixers. For now, only one "cleaner" exists: `suppressTypeError`, for adding `// @ts-expect-error` comments on any remaining type errors. I'll file a followup issue for adding `: any` the way `ts-migrate` does.

I wasn't planning on tackling this issue, but ended up having a few spare hours on a flight...

### CODE REVIEW

File: src/runtime/providers/createCleanupsProvider.ts [hunk 1]
```diff
@@ -0,0 +1,62 @@
...
+            }
+
+            return {
+                mutationsWave: {
+                    fileMutations: fileMutations.size === 0 ? undefined : (convertMapToObject(fileMutations) as Dictionary<Mutation[]>),
+                },
+            };
+        };
+    });
+};
```
Comment (JoshuaKGoldberg) [inline src/runtime/providers/createCleanupsProvider.ts:62]: In theory, I could extract the large amount of shared logic between `createCoreMutationsProvider` & `createCleanupsProvider` in some way... in practice, I'm not sure how this will exist post-#1000, so I'll leave as-is.
