### PR TITLE
test: enable suppressTypeErrors on all integration tests

### LINKED ISSUE #1548: 🧪 Tests: Enable suppressTypeErrors on all integration tests
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

By enabling suppressTypeErrors on all integration tests, we can easily see when there is non-valid code generated. 

We can see and fix following problems

- Incorrect compilerOptions.
- Bugs / missing fixes
- More examples of possible ts-expect-error comments

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by rubiesonthesky**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1548
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/TypeStat/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Enables `suppressTypeErrors` on all integration tests to track potential type errors on generated code.

Also, makes sure that we do not add absolute module path to the ts ignore comment as it would be different when run on different machines.

### CODE REVIEW

File: test/cases/fixes/incompleteTypes/returnTypes/expected.ts [hunk 1]
```diff
@@ -113,6 +116,7 @@
 	};
 
 	const returnsBigintOrNumber = (): number | bigint => {
+// @ts-expect-error -- TODO: BigInt literals are not available when targeting lower than ES2020.
```
Comment (JoshuaKGoldberg) [inline test/cases/fixes/incompleteTypes/returnTypes/expected.ts:119]: [Testing] Let's switch the test to use ESNext. Testing for this error isn't the point of the test.

File: test/cases/fixes/incompleteTypes/reactTypes/reactPropsMissing/expected.tsx [hunk 2]
```diff
@@ -99,11 +122,13 @@ prop: number[];
 
 	class SinglePropClassDeclaration extends React.Component<SinglePropClassDeclarationProps> {
 		render() {
+// @ts-expect-error -- TODO: Cannot use JSX unless the '--jsx' flag is provided.
 			return <div />;
 		}
 	}
 
 	const renderSinglePropClassDeclaration = () => (
+// @ts-expect-error -- TODO: Cannot use JSX unless the '--jsx' flag is provided.
```
Comment (JoshuaKGoldberg) [inline test/cases/fixes/incompleteTypes/reactTypes/reactPropsMissing/expected.tsx:131]: [Testing] Tests with `.tsx` files should enable the jsx flag.

File: test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromPropTypes/optionality/asWritten/expected.tsx [hunk 3]
```diff
@@ -1,4 +1,6 @@
+// @ts-expect-error -- TODO: This module can only be default-imported using the 'esModuleInterop' flag
 import React from "react";
+// @ts-expect-error -- TODO: This module can only be default-imported using the 'esModuleInterop' flag
```
Comment (JoshuaKGoldberg) [inline test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromPropTypes/optionality/asWritten/expected.tsx:3]: [Testing] This and other tests should have `esModuleInterop` enabled.

File: test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromPropTypes/all/original.tsx [hunk 4]
```diff
@@ -75,4 +75,34 @@ import PropTypes from "prop-types";
...
+	// TODO: The mutation for this is incorrect
+	function HelloWorldComponent({ name }) {
+		return <div>Hello, {name}</div>;
+	}
+
+	HelloWorldComponent.propTypes = {
+		name: PropTypes.string,
+	};
+
+	// TODO: The mutation for this is incorrect
```
Comment (JoshuaKGoldberg) [inline test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromPropTypes/all/original.tsx:98]: [Docs] For this and the other added `// TODO:`s, are issue(s) filed? If not, could you file one/them please?

File: test/cases/cleanups/nonTypeErrors/expected.ts [hunk 5]
```diff
@@ -0,0 +1,6 @@
+// @ts-expect-error -- TODO: This module can only be default-imported using the 'esModuleInterop' flag
+import ts from "typescript";
+// @ts-expect-error -- TODO: Cannot find module './typestat.json'. Consider using '--resolveJsonModule' to import module with '.json' extension.
```
Comment (JoshuaKGoldberg) [inline test/cases/cleanups/nonTypeErrors/expected.ts:3]: [Testing] The test should have `resolveJsonModule` so this gets imported nicely.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
OK! Thanks for the ping, and sorry this took so long. Kind of a behemoth to review 😅 but a very good step for comprehensive tests. Thank you for pushing it forward!

**Comment by JoshuaKGoldberg** [comment]
OH! That totally makes sense, I missed that. Agreed - thank you :)

**Review by JoshuaKGoldberg — APPROVED** [review]
You are absolutely right. 🚢 !~
