### PR TITLE
fix: NoInfereableTypes should not remove types from all consts

### LINKED ISSUE #1498: 🐛 Bug: noInferableTypes removes types from consts where it's not safe
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Keep there types

```ts
// map
const incompleteTypes: TypeSummariesPerNodeByName = new Map();
// array
const mutations: Mutation[] = [];
// function
export const fixIncompleteImplicitClassGenerics: FileMutator = (
	request: FileMutationsRequest,
) => collectMutationsFromNodes(request, ts.isClassLike, visitClassLike);
```

### Actual

This is the current output

```ts
// map
const incompleteTypes = new Map();
// array
const mutations = [];
// function
export const fixIncompleteImplicitClassGenerics = (
	request: FileMutationsRequest,
) => collectMutationsFromNodes(request, ts.isClassLike, visitClassLike);
```

### Additional Info

Continuing dogfooding this repo to TypeStat

typestat.json
```json
{
    "fixes": {
        "noInferableTypes": true
    },
    "include": [
        "src/**/*.{ts,tsx}"
    ],
    "projectPath": "./tsconfig.json"
}
```

---

I think the problem is here with this logic. It's not safe to say that you can remove types always from `const`. It's fine for primitive types like string, number or boolean. But for arrays, maps or sets it may not be safe.

```ts
const getNoInferableTypeVariableDeclarationMutation = (
	node: InferableVariableDeclaration,
	request: FileMutationsRequest,
) => {
	if (
		// `const` variables should always have their declarations removed
		tsutils.isNodeFlagSet(node.parent, ts.NodeFlags.Const) ||
		// `let` variables should have only uninformative declarations removed
		declaredInitializedTypeNodeIsRedundant(request, node.type, node.initializer)
	) {
		return createTypeRemovalMutation(request, node);
	}

	return undefined;
};
```

### PR DESCRIPTION
**Pull request by rubiesonthesky**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1498
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/TypeStat/blob/main/.github/CONTRIBUTING.md) were taken 🐙 

## Overview

It's not safe to remove type from const always. I think the mutation tests agree with me. Some things are marked as "non-inferable" but still their types were removed.

### CODE REVIEW

File: test/cases/fixes/noInferableTypes/variableDeclarations/expected.ts [hunk 1]
```diff
@@ -47,8 +47,8 @@
 	let letInferableNumberOrRegExps = [0, /./];
 
 	// Non-inferable const multi-type arrays
```
Comment (JoshuaKGoldberg) [inline test/cases/fixes/noInferableTypes/variableDeclarations/expected.ts:49]: [Docs] These are inferable now! 

```suggestion
	// Inferable const multi-type arrays
```

File: test/cases/fixes/noInferableTypes/variableDeclarations/expected.ts [hunk 2]
```diff
@@ -65,22 +65,41 @@
 	let letTakesChild = new Child();
 
 	// Non-inferable const direct class instances
```
Comment (JoshuaKGoldberg) [inline test/cases/fixes/noInferableTypes/variableDeclarations/expected.ts:67]:
```suggestion
	// Inferable const direct class instances
```

...honestly, if you want to just delete all these existing comments, I'd be up for that too. In the years since writing I've grown much less fond of comments that basically restate the code. And these are IMO a symptom of the test being ripe for splitting up, per #1504.

**Review by JoshuaKGoldberg — APPROVED** [review]
LGTM, thanks! Always nice to see source code line removal that improves something. ❤️‍🔥 

I defer to your preference on the comments. Whatever you think is reasonable 😄. And then, you should have permission to merge, lmk if not.

File: test/cases/fixes/noInferableTypes/variableDeclarations/expected.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply test/cases/fixes/noInferableTypes/variableDeclarations/expected.ts:49]: Ah, right. Thanks 😄
