### PR TITLE
React props from later uses

### LINKED ISSUE #761: React components don't have extra prop inferences when not directly used
### 🐛 Bug Report

-   TypeStat version: 0.4.1
-   TypeScript version: 4.1.2
-   Node version: N/A

#### Actual Behavior

`fixReactPropsFromLaterAssignments` -> `getComponentAssignedTypesFromUsage` only looks at direct end-user usages of the component. This kind of thing works:

```tsx
type MyComponentProps = { stringOrNumber : string };
const MyComponent: React.FC<MyComponentProps> = ({ stringOrNumber }) => <span>{stringOrNumber }</span>;

const rendered = <MyComponent stringOrNumber={7}/>;
```

...but this would not:

```tsx
const ConnectedMyComponent = connect(MyComponent)(/* ... */);

// (or provided by mapStateToProps, etc.
const connected = <ConnectedMyComponent stringOrNumber={7}/>;
```

#### Expected Behavior

I think they'll also need to be informed by `this.props.*` usage.

#### Reproduction

I've been testing on internal code to Codecademy, sorry if the above is unclear future readers!

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## PR Checklist

-   [x] Addresses an existing issue: fixes #761
-   [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/TypeStat/labels/status%3A%20accepting%20prs)

## Overview

Adds type expansions for React prop values from two kinds of uses:

* Being passed to a JSX element attribute
* Being passed as an argument to a function

### CODE REVIEW

File: test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromUses/expected.tsx [hunk 1]
```diff
@@ -0,0 +1,36 @@
+import * as React from 'react';
+
+(function () {
+    interface FromUsesComponentProps {
+        returnsBoolean: () => unknown | (() => boolean);
+        takesStringCall: () => void | ((text: string) => void);
+        takesStringJsx: () => void | ((text: string) => string);
```
Comment (JoshuaKGoldberg) [inline test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromUses/expected.tsx:7]: These should really be replacements, not union types...

File: test/cases/fixes/incompleteTypes/reactTypes/reactPropFunctionsFromCalls/original.tsx [hunk 2]
```diff
@@ -26,11 +26,11 @@ import * as React from 'react';
...
-        providesNothing: () => void;
-        providesString: (arg0: string) => void;
-        providesNumberThenString: (arg0: number, arg1: string) => void;
-        providesBooleanGivesNumber: (arg0: boolean) => number;
-        returnsString: () => string;
+        providesNothing: Function;
+        providesString: Function;
+        providesNumberThenString: Function;
+        providesBooleanGivesNumber: Function;
+        returnsString: Function;
```
Comment (JoshuaKGoldberg) [inline test/cases/fixes/incompleteTypes/reactTypes/reactPropFunctionsFromCalls/original.tsx:33]: 🤔 how unfortunate. I think the tests are hamstrung by only being able to run one round of mutation. I'll probably have to reconfigure them to run up to some arbitrary >1 number.

Comment (JoshuaKGoldberg) [reply test/cases/fixes/incompleteTypes/reactTypes/reactPropFunctionsFromCalls/original.tsx:33]: (...or maybe this is just an introduced bug?)

File: test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromUses/expected.tsx (hunk 1 above)
Comment (JoshuaKGoldberg) [reply test/cases/fixes/incompleteTypes/reactTypes/reactPropsFromUses/expected.tsx:7]: I'm going to switch these to `unknown`s to start. There are more issues that I think will come down the pipeline about better resolution around functions and union types. In the meantime, this scenario is unlikely.
