### PR TITLE
fix: no longer removing Map or Set type when they are needed

### LINKED ISSUE #1512: 🐛 Bug: noInferableTypes removes incorrectly type from Map variable
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

This code stays as it is

```ts
type MapStringToNumber = Map<string, number>;
const incompleteTypes: MapStringToNumber = new Map();
```

### Actual

It changes to

```ts
type MapStringToNumber = Map<string, number>;
const incompleteTypes = new Map();
```

### Additional Info

This was uncovered with changes in https://github.com/JoshuaKGoldberg/TypeStat/pull/1511 

typestat.json
```json
{
	"fixes": {
		"noInferableTypes": true
	},
	"types": {
		"strictNullChecks": true
	}
}
```

tsconfig
```json
{
	"files": ["actual.ts"]
}
```

### PR DESCRIPTION
**Pull request by rubiesonthesky**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1512
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/TypeStat/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

I'm not sure that this is correct place to place this code. It's also maybe too heavy handed. But on the other hand, I think it's better to prevent cases where we introduce implicit anys when there was some type earlier. Keeping types that could have been removed, is less bad in that case.

I have tried to find what would be right place to do this check but I did not have any luck.

### CODE REVIEW

File: src/shared/comparisons.ts [hunk 1]
```diff
@@ -57,11 +57,22 @@ export const declaredInitializedTypeNodeIsRedundant = (
...
-	);
+	const typeChecker = request.services.program.getTypeChecker();
+
+	const declaredEscapedName = declaredType.getSymbol()?.getEscapedName();
+
+	// This is brute-force way to keep Map<string, number> comparison to Map without type arguments...
+	// This will allow many type declarations that could be removed.
+	if (
+		// eslint-disable-next-line @typescript-eslint/no-unsafe-enum-comparison
+		(declaredEscapedName === "Map" || declaredEscapedName === "set") &&
```
Comment (JoshuaKGoldberg) [inline src/shared/comparisons.ts:68]:
```suggestion
		(declaredEscapedName === "Map" || declaredEscapedName === "Set") &&
```

File: test/cases/fixes/noInferableTypes/variableDeclarations/original.ts
Comment (JoshuaKGoldberg) [inline test/cases/fixes/noInferableTypes/variableDeclarations/original.ts:1]: [Testing] A few more cases come to mind...
* `let stringMapTyped: Map<string, string | number> = new Map<string, number>();`: should keep the type annotation, I think?
* `ReadonlyMap`
* Custom generic classes like `class MyMap<K, V> { ... }`
* `type` aliases

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
I think this is a good start but there are some tricky edge cases that I worry might make this a lot more complex than it seems. Good luck! ✨

File: src/shared/comparisons.ts [hunk 2]
```diff
@@ -57,18 +51,38 @@ export const declaredInitializedTypeNodeIsRedundant = (
...
-	);
+	const typeChecker = request.services.program.getTypeChecker();
+
+	const declaredText = declaredType.getSymbol()?.getEscapedName();
+
+	// This is brute-force way to keep Map<string, number> comparison to Map without type arguments...
+	// This will allow many type declarations that could be removed.
+	if (
+		// eslint-disable-next-line @typescript-eslint/no-unsafe-enum-comparison
+		(declaredText === "Map" ||
```
Comment (JoshuaKGoldberg) [inline src/shared/comparisons.ts:62]: I feel very icky about hardcoding to Maps & Sets by name 😬. Those two classes just so happen to be declared in `lib.es*.d.ts`. Users might declare their own classes that we'd want to have the same kind of fixing behavior on. Same with interfaces like `Readonlymap`.

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]

File: src/shared/comparisons.ts [hunk 3]
```diff
@@ -2,17 +2,17 @@ import * as tsutils from "ts-api-utils";
...
+	getTypeAtLocationIfNotError,
+	getTypeAtLocationIfNotErrorWithChecker,
+} from "./types.js";
 
 export const declaredInitializedTypeNodeIsRedundant = (
 	request: FileMutationsRequest,
 	declaration: ts.TypeNode,
 	initializer: ts.Node,
-) => {
+): boolean | undefined => {
```
[the remark this answers is not in the document]
Comment (JoshuaKGoldberg) [reply src/shared/comparisons.ts:15]: 🤷 I don't have a hard preference either way 😄

File: src/shared/comparisons.ts [hunk 4]
```diff
@@ -36,14 +36,8 @@ export const declaredInitializedTypeNodeIsRedundant = (
...
 	// `RegExp`s are also initializers that one should never reassign
-	if (
-		ts.isTypeReferenceNode(declaration) &&
-		ts.isIdentifier(declaration.typeName)
-	) {
-		switch (declaration.typeName.text) {
-			case "RegExp":
-				return initializer.kind === ts.SyntaxKind.RegularExpressionLiteral;
-		}
+	if (ts.isRegularExpressionLiteral(declaration)) {
```
[the remark this answers is not in the document]
Comment (JoshuaKGoldberg) [reply src/shared/comparisons.ts:39]: No preference on my end 😄

File: src/shared/comparisons.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [reply src/shared/comparisons.ts:69]: Yeah I think it sets a bad precedent. I have actually seen a bunch of codebases use real names like `Map` and `Set`. And the older the codebase, the more likely it wants a tool like TypeStat to help it migrate!

**Review by JoshuaKGoldberg — APPROVED** [review]
Looks great to me, thanks!

I've context switched away from TypeStat for a bit to focus on ESLint stuff. Sorry that reviewing is taking a while. But I'm still very excited you're looking at all this! 🙌
