### PR TITLE
fix: incompleteReturnTypes: async function can only return Promises

### LINKED ISSUE #1494: 🐛 Bug: Added type should be Promise<boolean> not Promise<boolean> | boolean
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

This function is not missing return types

```ts
	function navigateByUrl(url: string): Promise<boolean>;

	async function navigateTo(): Promise<boolean> {
		return await navigateByUrl("");
	}
```

### Actual

However, it's "fixed" into this

```ts
       function navigateByUrl(url: string): Promise<boolean>;

	async function navigateTo(): Promise<boolean> | boolean {
		return await navigateByUrl("");
	}
```

### Additional Info

See discussion https://github.com/JoshuaKGoldberg/TypeStat/pull/1481/files#r1545469119 

tsconfig.json
```json 
{
	"files": ["actual.ts"]
}
```

typestat.json
```json
{
	"fixes": {
		"incompleteTypes": true
	},
	"types": {
		"strictNullChecks": true
	}
}
```

The problem seems to lie when using `await` or other promise kinds. If function is marked as async, it would be safer to put all types inside Promise.

### PR DESCRIPTION
**Pull request by rubiesonthesky**
## PR Checklist

- [x] Addresses an existing open issue: fixes #1494
- [x] That issue was marked as [`status: accepting prs`](https://github.com/JoshuaKGoldberg/TypeStat/issues?q=is%3Aopen+is%3Aissue+label%3A%22status%3A+accepting+prs%22)
- [x] Steps in [CONTRIBUTING.md](https://github.com/JoshuaKGoldberg/TypeStat/blob/main/.github/CONTRIBUTING.md) were taken

## Overview

Wrap inside Promise, if one of the existing types mentions Promise.

### CODE REVIEW

File: src/mutations/creators.ts [hunk 1]
```diff
@@ -53,24 +54,46 @@ export const createTypeAdditionMutation = (
...
-			range: {
-				begin: node.type.pos,
-				end: node.type.end,
-			},
-			type: "text-swap",
-		};
+		return textSwap(` ${newTypeAlias}`, node.type.pos, node.type.end);
+	}
+
+	const isAsyncFunction =
```
Comment (JoshuaKGoldberg) [inline src/mutations/creators.ts:60]: [Refactor] 🤔 `createTypeAdditionMutation` is meant to be a pretty generalized utility. It doesn't understand anything about the types: just that there's a single `declaredType` and an array of `allAssignedTypes`. I don't think this is the right place to add logic specific to async functions.

Given that this PR is only meant to touch `fixIncompleteReturnTypes`, I think the logic should exist there. That would be a place to put logic around promises.

File: src/mutations/creators.ts [hunk 2]
```diff
@@ -53,24 +54,46 @@ export const createTypeAdditionMutation = (
...
+	const typeChecker = request.services.languageService
+		.getProgram()
+		?.getTypeChecker();
+
+	const typesAsPromises = new Set(
+		[...missingTypes].map((type) => {
+			const stringified = typeChecker?.typeToString(
+				typeChecker.getBaseTypeOfLiteralType(type),
+			);
+			return stringified?.startsWith("Promise<")
```
Comment (JoshuaKGoldberg) [inline src/mutations/creators.ts:78]: [Bug] If the user defines their own `Promise<` class/type, this will false positive. 

You'll want to use something like https://typescript-eslint.io/packages/type-utils#issymbolfromdefaultlibrary instead of a stringification check.

File: src/mutations/creators.ts [hunk 3]
```diff
@@ -53,24 +54,46 @@ export const createTypeAdditionMutation = (
...
+		node.modifiers?.some((modifier) => tsutils.isAsyncKeyword(modifier));
+
+	if (!isAsyncFunction) {
+		// Create a mutation insertion that adds the missing types in
+		return textInsert(` | ${newTypeAlias}`, node.type.end);
+	}
+
+	const typeChecker = request.services.languageService
+		.getProgram()
+		?.getTypeChecker();
```
Comment (JoshuaKGoldberg) [inline src/mutations/creators.ts:71]: [Types] The type checker should never be undefined. One is available under:

```suggestion
	const typeChecker = request.services.program.getTypeChecker();
```

File: src/mutations/text-mutations.ts
Comment (JoshuaKGoldberg) [inline src/mutations/text-mutations.ts:1]: [Praise] Good idea! I like how much more readable the `creators.ts` functions are now. 🙂 nice!

**Review by JoshuaKGoldberg — CHANGES_REQUESTED** [review]
Nifty idea, I like the targeting of async functions. 💪

**Review by JoshuaKGoldberg — APPROVED** [review]
🚀 Awesome!
